#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $DIR
cd $DIR
if [[ ! -f $DIR/fifo ]]; then
	mkfifo fifo
fi
#$1 < $DIR/fifo |echo|lua $DIR/main.lua ${@:2} > fifo
lua $DIR/main.lua $@